# Generated by Django 5.0 on 2023-12-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('unitPrice', models.CharField(max_length=100)),
                ('qtyOnHand', models.CharField(max_length=100)),
            ],
        ),
    ]
