# Generated by Django 5.0 on 2023-12-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0001_initial'),
    ]

    operations = [
    ]
