# Generated by Django 5.0 on 2023-12-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0002_auto_20231228_2037'),
    ]

    operations = [
    ]
