# Generated by Django 5.0 on 2023-12-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0003_auto_20231228_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='qtyOnHand',
            new_name='quantity',
        ),
    ]
