# Generated by Django 5.0 on 2023-12-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
    ]
